<?php

namespace MedecinBundle\Repository;

/**
 * InfoSanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoSanteRepository extends \Doctrine\ORM\EntityRepository
{
}
