<?php

namespace AnimateurBundle\Repository;

/**
 * Animateur_formationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Animateur_formationRepository extends \Doctrine\ORM\EntityRepository
{
}
