user_homepage:
    path:     /
    defaults: { _controller: UserBundle:Default:index }
Page_Parent:
    path:     /pageParent
    defaults: { _controller: UserBundle:Default:Parent }

Page_Admin:
    path:     /admin
    defaults: { _controller: UserBundle:Default:Admin }

Page_Responsable:
    path:     /pageResponsable
    defaults: { _controller: UserBundle:Default:Responsable }
