<?php

namespace EnfantBundle\Repository;

/**
 * enfantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class enfantRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByParent($id)
    {
        $query=$this->getEntityManager()->createQuery(
            "select A from EnfantBundle:enfant A where A.parent = :id"
        )
            ->setParameter(':id', $id)
        ;

        return $query->getResult();
    }
    public function findNumber($garderie)
    {
        $query=$this->getEntityManager()->createQuery(
            "select A from EnfantBundle:enfant A where A.garderie = :id"
        )
            ->setParameter(':id', $garderie)
        ;

        return $query->getResult();
    }
}
