<?php

namespace EnfantBundle\Repository;

/**
 * suiviRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class suiviRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByEnfant($id)
    {
        $query=$this->getEntityManager()->createQuery(
            "select A from EnfantBundle:suivi A where A.enfant = :id"
        )
            ->setParameter(':id', $id)
            ;

        return $query->getResult();
    }
}
